name: RDS Booking System CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  # Prevents triggering on commits made by GitHub Actions
    paths-ignore:
      - "query_results.yaml"

jobs:
  setup:
    runs-on: ubuntu-latest  # We will run this job on an Ubuntu environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # This checks out the code from the repository

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install -y unixodbc-dev
        pip install -r requirements.txt  # Install dependencies from your requirements.txt

    - name: Set up SSH for EC2 connection
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        eval $(ssh-agent -s)
        ssh-add private_key.pem
    - name: Upload files to EC2 using rsync
      run: |
        # Install rsync on EC2 if it's not already installed
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "sudo yum install -y rsync"
        # Ensure the target directory exists before uploading
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "mkdir -p /home/ec2-user/booking_system" 
        # Use rsync to upload files while excluding the .git directory
        rsync -avz --exclude '.git' -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/booking_system
        - name: Install necessary tools on EC2
      run: |
        # SSH into EC2 and install tools
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          # Update system and install prerequisites
          sudo yum update -y
          sudo yum install -y python3-devel unixODBC-devel glibc libgcc

          # Install Microsoft ODBC Driver 17 for SQL Server
          if ! rpm -q msodbcsql17; then
            echo "Installing ODBC Driver 17 for SQL Server..."
            # Add Microsoft repository for Amazon Linux 2 (closest match)
            sudo curl -o /etc/yum.repos.d/msprod.repo https://packages.microsoft.com/config/amazonlinux/2/prod.repo
            
            # Try installing with yum first
            sudo yum install -y msodbcsql17
            if [ $? -ne 0 ]; then
              echo "Yum installation failed, attempting manual RPM install..."
              # Download the RPM directly and install with --noscripts to skip PREIN
              curl -o msodbcsql17.rpm https://packages.microsoft.com/amazonlinux/2/prod/pool/main/m/msodbcsql17/msodbcsql17-17.10.6.1-1.x86_64.rpm
              sudo rpm -ivh --noscripts msodbcsql17.rpm
              if [ $? -ne 0 ]; then
                echo "Manual RPM installation failed!"
                exit 1
              fi
            fi
            sudo yum clean all
          else
            echo "msodbcsql17 is already installed."
          fi

          # Locate the actual ODBC driver library
          DRIVER_PATH=$(find /opt/microsoft/msodbcsql17/lib64 -name 'libmsodbcsql-17.*.so.*' | head -n 1)
          if [ -z "$DRIVER_PATH" ]; then
            echo "Error: No ODBC Driver 17 library found in /opt/microsoft/msodbcsql17/lib64!"
            ls -l /opt/microsoft/msodbcsql17/lib64/ || echo "Directory not found!"
            exit 1
          fi
          echo "Found ODBC Driver library at: $DRIVER_PATH"

          # Register the driver with unixODBC
          sudo bash -c "cat > /etc/odbcinst.ini << 'CONFIG'
          [ODBC Driver 17 for SQL Server]
          Description=Microsoft ODBC Driver 17 for SQL Server
          Driver=$DRIVER_PATH
          CONFIG"

          # Install Python dependencies
          pip3 install --upgrade pip
          pip3 install -r /home/ec2-user/booking_system/requirements.txt

          # Verify driver registration
          echo "Registered ODBC drivers:"
          odbcinst -q -d
          echo "ODBC Driver setup completed successfully."
        EOF
  
    - name: Run database setup and booking trigger scripts on EC2
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/booking_system
          python3 db_setup.py  # Run the setup script to create DB, tables and insert data
          python3 booking_trigger.py  # Run the booking trigger script to insert bookings and calculate costs
        EOF

    - name: Run custom SQL queries on EC2 and fetch results
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/booking_system
          python3 run_queries.py  # Run the custom query script to fetch results
        EOF

    - name: Commit and push query results back to repository
      run: |
        git add query_results.yaml  # Add the file containing the results of the query
        git commit -m "Automated update from EC2 query results"
        git push origin main  # Push the changes to the main branch

 